require('settings')
require('plugins')
require('lsp')
require('completion')
require('telescope-setup')
require('setup-treesitter')
require('surround')
require('comment')
require('git')
require('autopairs')

require('keymaps')
